name: zombie_yahtzee
description: A yahtzee clone with a zombie theme.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/cards/
    - images/cards/selected/
    - images/cards/unselected/
    - images/dice/selected/
    - images/dice/unselected/
    - images/letters/green/
    - images/letters/red/
    - images/letters/tan/
    - images/logos/
    - images/numbers/
    - images/numbers/green/
    - images/numbers/red/
    - images/numbers/tan/
    - images/roll_count/
    - images/undo/
    - images/zombie_count/

  fonts:
    - family: OctoberCrow
      fonts:
        - asset: fonts/OctoberCrow.ttf